name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x    
    - name: Restore dependencies
      run: cd TestingCICD && dotnet restore
    - name: Build
      run: cd TestingCICD && dotnet build --no-restore
    - name: Test
      run: cd TestingCICD && dotnet test --no-build --verbosity normal
    
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: 129.151.98.40
        username: ubuntu
        key: ${{ secrets.UBUNTUSSHKEY }}
        port: ${{ secrets.PORT }}
        script: ./AutoDeployPoloMC.sh
    
    
     
        
