name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x    
    - name: Restore dependencies
      run: dotnet restore -p TestingCICD
    - name: Build
      run: dotnet build -p TestingCICD --no-restore
    - name: Test
      run: dotnet test -p TestingCICD --no-build --verbosity normal
