name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x    
    - name: Restore dependencies
      run: cd TestingCICD && dotnet restore
    - name: Build
      run: cd TestingCICD && dotnet build --no-restore
    - name: Test
      run: cd TestingCICD && dotnet test --no-build --verbosity normal
    - name: SSH command runner
    # You may pin to the exact commit or the version.
    # uses: Evaneos/ssh-action@0e5f8933569a924cad91d22e30f7ecfb5d8426f2
      uses: Evaneos/ssh-action@v0.1.0
      with:
        # Remote host(s) to connect to
        hosts: 129.151.98.40
        # One or multiple commands to run on the remote host(s)
        commands: ./AutoDeployPoloMC.sh
        # Remote user to connect with
        user: ubuntu                
        # Private SSH key to connect with
        private_key: ${{ secrets.UBUNTUSSHKEY }}
        
        
        
        
    
    
    session_timeout: # optional
